EXEC sp_student 
    @opt = 3,
    @first_name = 'Jose',
    @middle_name = 'Ángel',
    @last_name = 'Martínez',
    @gender = 'M',
    @address_line = 'Av. Monterrey 456',
    @city = 'Monterrey',
    @zip_postcode = '64000',
    @state = 'Nuevo León',
    @email = 'miguel.martinez@example.com',
    @email_type = 'Personal',
    @phone = '8123456789',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Luis',
    @middle_name = 'Enrique',
    @last_name = 'Pérez',
    @gender = 'M',
    @address_line = 'Calle Hidalgo 789',
    @city = 'San Pedro Garza García',
    @zip_postcode = '66220',
    @state = 'Nuevo León',
    @email = 'luis.perez@example.com',
    @email_type = 'Personal',
    @phone = '8112345678',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'María',
    @middle_name = 'Guadalupe',
    @last_name = 'López',
    @gender = 'F',
    @address_line = 'Calle Juárez 321',
    @city = 'Guadalupe',
    @zip_postcode = '67100',
    @state = 'Nuevo León',
    @email = 'maria.lopez@example.com',
    @email_type = 'Personal',
    @phone = '8123456780',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'José',
    @middle_name = 'Manuel',
    @last_name = 'Hernández',
    @gender = 'M',
    @address_line = 'Calle Zaragoza 654',
    @city = 'Apodaca',
    @zip_postcode = '66600',
    @state = 'Nuevo León',
    @email = 'jose.hernandez@example.com',
    @email_type = 'Personal',
    @phone = '8187654321',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Juan',
    @middle_name = 'Carlos',
    @last_name = 'García',
    @gender = 'M',
    @address_line = 'Calle Morelos 987',
    @city = 'Santa Catarina',
    @zip_postcode = '66350',
    @state = 'Nuevo León',
    @email = 'juan.garcia@example.com',
    @email_type = 'Personal',
    @phone = '8115678901',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Raúl',
    @middle_name = 'Alejandro',
    @last_name = 'Rodríguez',
    @gender = 'M',
    @address_line = 'Blvd. Constitución 112',
    @city = 'San Nicolás de los Garza',
    @zip_postcode = '66400',
    @state = 'Nuevo León',
    @email = 'raul.rodriguez@example.com',
    @email_type = 'Personal',
    @phone = '8181234567',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Elena',
    @middle_name = 'Sofía',
    @last_name = 'Ramírez',
    @gender = 'F',
    @address_line = 'Calle Colón 443',
    @city = 'Escobedo',
    @zip_postcode = '66050',
    @state = 'Nuevo León',
    @email = 'elena.ramirez@example.com',
    @email_type = 'Personal',
    @phone = '8187654320',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Patricia',
    @middle_name = 'Lorena',
    @last_name = 'Gómez',
    @gender = 'F',
    @address_line = 'Av. Revolución 567',
    @city = 'Monterrey',
    @zip_postcode = '64800',
    @state = 'Nuevo León',
    @email = 'patricia.gomez@example.com',
    @email_type = 'Personal',
    @phone = '8129876543',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '81';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Carlos',
    @middle_name = 'Eduardo',
    @last_name = 'Ruiz',
    @gender = 'M',
    @address_line = 'Calle Hidalgo 678',
    @city = 'Hermosillo',
    @zip_postcode = '83200',
    @state = 'Sonora',
    @email = 'carlos.ruiz@example.com',
    @email_type = 'Personal',
    @phone = '6623456789',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '662';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Ana',
    @middle_name = 'Carolina',
    @last_name = 'Vázquez',
    @gender = 'F',
    @address_line = 'Calle Obregón 345',
    @city = 'Cajeme',
    @zip_postcode = '85000',
    @state = 'Sonora',
    @email = 'ana.vazquez@example.com',
    @email_type = 'Personal',
    @phone = '6441234567',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '644';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Roberto',
    @middle_name = 'Antonio',
    @last_name = 'Santos',
    @gender = 'M',
    @address_line = 'Calle Guerrero 789',
    @city = 'Nogales',
    @zip_postcode = '84000',
    @state = 'Sonora',
    @email = 'roberto.santos@example.com',
    @email_type = 'Personal',
    @phone = '6312345678',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '631';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Laura',
    @middle_name = 'Beatriz',
    @last_name = 'Ortega',
    @gender = 'F',
    @address_line = 'Calle Morelos 987',
    @city = 'Guaymas',
    @zip_postcode = '85400',
    @state = 'Sonora',
    @email = 'laura.ortega@example.com',
    @email_type = 'Personal',
    @phone = '6223456789',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '622';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Fernando',
    @middle_name = 'Andrés',
    @last_name = 'Méndez',
    @gender = 'M',
    @address_line = 'Calle Serdán 432',
    @city = 'Navojoa',
    @zip_postcode = '85800',
    @state = 'Sonora',
    @email = 'fernando.mendez@example.com',
    @email_type = 'Personal',
    @phone = '6423456780',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '642';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Paola',
    @middle_name = 'María',
    @last_name = 'Cruz',
    @gender = 'F',
    @address_line = 'Calle Allende 654',
    @city = 'Ciudad Obregón',
    @zip_postcode = '85000',
    @state = 'Sonora',
    @email = 'paola.cruz@example.com',
    @email_type = 'Personal',
    @phone = '6445678901',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '644';

EXEC sp_student 
    @opt = 3,
    @first_name = 'Raúl',
    @middle_name = 'Jesús',
    @last_name = 'Luna',
    @gender = 'M',
    @address_line = 'Calle Matamoros 321',
    @city = 'Hermosillo',
    @zip_postcode = '83200',
    @state = 'Sonora',
    @email = 'raul.luna@example.com',
    @email_type = 'Personal',
    @phone = '6625678901',
    @phone_type = 'Personal',
    @country_code = '52',
    @area_code = '662';
